#!/bin/bash -e

JOBS=${JOBS-100}
SINGULAR_SCRIPT=$(echo $0 | sed -e "s/pods_/pod_/" | sed -e "s/nodes_/node_/g" | sed -e "s/pods$/pod/" | sed -e "s/nodes$/node/")
parallel -j$JOBS -k $SINGULAR_SCRIPT "$@" {}
