#!/bin/bash -eu

GCE_CLUSTER_NAME=${GCE_CLUSTER_NAME-seagull}

#echo "[*] Node Pools"
#gcloud container node-pools list --cluster $GCE_CLUSTER_NAME

echo ""
echo "[*] Instances"
gcloud compute instances list | grep -E "STATUS|RUNNING"

echo ""
echo "[*] Disks"
gcloud compute disks list
