#!/bin/bash -eu

RESULT_INSTANCE=$(gcloud compute disks describe $GCE_DISK_NAME | grep -A1 users | tail -n1 | sed -e s=.*/==)

gcloud compute ssh $RESULT_INSTANCE --command " \
	sudo mkdir -p /mnt/disks/$GCE_DISK_NAME; \
	sudo umount -l /mnt/disks/$GCE_DISK_NAME; \
	sudo mount -o bind /var/lib/kubelet/plugins/kubernetes.io/gce-pd/mounts/$GCE_DISK_NAME /mnt/disks/$GCE_DISK_NAME"

gcloud compute ssh chronos@$RESULT_INSTANCE --command="echo [+] Updated ssh metadata"
SSH_DEST=$(gcloud compute ssh chronos@$RESULT_INSTANCE --dry-run | sed -e "s/.* //")

ssh-keyscan ${SSH_DEST##*@} >> ~/.ssh/known_hosts
sshfs $SSH_DEST:/mnt/disks/$GCE_DISK_NAME $1
