#!/bin/bash

if [ $# -gt 0 ]
then
	# thanks to https://stackoverflow.com/questions/12283463/in-bash-how-do-i-join-n-parameters-together-as-a-string
	IFS="-"
	echo "$*"
else
	cat
fi | tr " _,.+" "----+" | tr -d -C '[:alnum:]-\n' | tr '[:upper:]' '[:lower:]'
