#!/bin/bash

MOUNT_POINT=${1-/mnt/kube-nfs}

echo "[*] Shutting down local NFS servers (to free ports)"
sudo service nfs-kernel-server stop
sudo service rpcbind stop

echo "[*] Forwarding NFS ports to kubernetes"
sudo kubectl port-forward service/nfs-service 2049 20048 111 &
sleep 5

echo "[*] Mounting NFS share at $MOUNT_POINT"
sudo mkdir -p $MOUNT_POINT
sudo mount 127.0.0.1:/exports/results $MOUNT_POINT

echo "[*] NFS share mounted at $MOUNT_POINT. Press Ctrl-C to unmount and disable mapping"
trap 'echo "[*] Unmounting $MOUNT_POINT"; sudo umount $MOUNT_POINT' EXIT
wait
