#!/bin/bash -eu

function join_by { local IFS="$1"; shift; echo "$*"; }

STATUS_FILTERS=( )
AWK_FILTER='{print$1}' 
EXTRA_ARGS=${EXTRA_ARGS-}

while getopts "spcrfow" OPT
do
	case $OPT in
		s)
			STATUS_FILTERS+=(Successful)
			;;
		p)
			STATUS_FILTERS+=(Pending)
			;;
		c)
			STATUS_FILTERS+=(ContainerCreating)
			;;
		r)
			STATUS_FILTERS+=(Running)
			;;
		f)
			STATUS_FILTERS+=(Failed)
			;;
		o)
			STATUS_FILTERS+=(OOMKilled)
			;;
		w)
			AWK_FILTER='{print}'
			EXTRA_ARGS='-owide'
			;;
	esac
done

if [ ${#STATUS_FILTERS[@]} -eq 0 ]
then
	STATUS_REGEX=".*"
else
	STATUS_REGEX=" ($(join_by \| "${STATUS_FILTERS[@]}")) "
fi

HOST_REGEX=${@:$OPTIND:1}
[ -z "$HOST_REGEX" ] && HOST_REGEX=".*"

kubectl get pods -n $EXPERIMENT -a $EXTRA_ARGS | tail -n+2 | grep -E "$STATUS_REGEX" | awk $AWK_FILTER | grep -E "$HOST_REGEX"
