#!/bin/bash -u

# first, get the freaking json
ORIGINAL_JSON=$(kubectl run --restart Never --dry-run=client -o json "$@")
MODIFIED_JSON=$(echo $ORIGINAL_JSON | jq '.spec.containers[] += {volumeMounts: [ {name: "nfs", mountPath: "/shared"} ], stdin: true, tty: true}' | jq '.spec += {volumes: [ {name: "nfs", persistentVolumeClaim: { claimName: "nfs" } } ] }')

# now launch!

exec kubectl run --pod-running-timeout=999h --restart=Never -it --rm --overrides="$MODIFIED_JSON" "$@"
