#!/bin/bash -eu

DOCKER_USER=$1
DOCKER_PASS=$2
DOCKER_SERV=$3

echo "[*] Creating docker registry secret $EXPERIMENT-secret!"
if kubectl get secret docker-secret 2>/dev/null >/dev/null
then
	echo "[+] docker-secret already exists! You can remove it with:"
	echo "# kubectl delete secret docker-secret"
	exit 1
fi

ARGS="--docker-username=$DOCKER_USER --docker-password=$DOCKER_PASS"
if [ -n "${DOCKER_SERV-}" ]
then
	ARGS="$ARGS --docker-server=$DOCKER_SERV"
fi
kubectl create secret docker-registry docker-secret $ARGS --docker-email=go-away@asdf.com
